package ru.den.writes.code.project01.cliJvm

/**
 * Per-model pricing and context-window data used to derive cost from
 * a token count.
 *
 * Rates are in USD per 1,000,000 tokens — that's how providers quote them.
 * [contextWindowTokens] is the input-side limit (prompt + history). null
 * means "unknown / not modelled here".
 *
 * Thinking-capable Gemini models bill their reasoning tokens at the
 * output rate, hence the cost formula in [PricingRegistry.cost] adds
 * `thoughtsTokens` to `outputTokens` before applying the output rate.
 */
internal data class ModelPricing(
    val inputUsdPer1M: Double,
    val outputUsdPer1M: Double,
    val contextWindowTokens: Int? = null,
)

/**
 * Static, hand-maintained lookup of [ModelPricing] by provider-specific
 * model id (the same string that travels on the wire). Updated by hand
 * when a new model shows up or rates change.
 *
 * Models not in the map produce `null` on [lookup]; the caller
 * (typically [SessionStats.seedFrom] or the per-turn footer printer)
 * treats that as "we don't know the cost" and prints a `$? (no pricing)`
 * marker instead of guessing.
 *
 * Rates current as of June 2026. Sources:
 * - Gemini: https://ai.google.dev/gemini-api/docs/pricing
 * - OpenRouter free roster (all 0/0): https://openrouter.ai/models?max_price=0
 */
internal object PricingRegistry {
    private val byId: Map<String, ModelPricing> = mapOf(
        // ---- Gemini text models (paid tier) -----------------------------
        // 2.5 Pro: tiered pricing (≤200K vs >200K). We use the lower tier
        // here as an approximation — most chat sessions stay under 200K.
        "gemini-2.5-pro" to ModelPricing(
            inputUsdPer1M = 1.25,
            outputUsdPer1M = 10.00,
            contextWindowTokens = 2_000_000,
        ),
        "gemini-2.5-flash" to ModelPricing(
            inputUsdPer1M = 0.30,
            outputUsdPer1M = 2.50,
            contextWindowTokens = 1_000_000,
        ),
        "gemini-2.5-flash-lite" to ModelPricing(
            inputUsdPer1M = 0.10,
            outputUsdPer1M = 0.40,
            contextWindowTokens = 1_000_000,
        ),

        // 3.x preview/GA. Numbers below are from the project's prior
        // experiments; adjust against Google's pricing page if they
        // change.
        "gemini-3.1-pro-preview" to ModelPricing(
            inputUsdPer1M = 1.25,
            outputUsdPer1M = 10.00,
            contextWindowTokens = 1_000_000,
        ),
        // The id literally omits the `.1` — that's how Google ships it.
        "gemini-3-flash-preview" to ModelPricing(
            inputUsdPer1M = 0.50,
            outputUsdPer1M = 3.00,
            contextWindowTokens = 1_000_000,
        ),
        "gemini-3.1-flash-lite" to ModelPricing(
            inputUsdPer1M = 0.10,
            outputUsdPer1M = 0.40,
            contextWindowTokens = 1_000_000,
        ),
        "gemini-3.5-flash" to ModelPricing(
            inputUsdPer1M = 1.50,
            outputUsdPer1M = 9.00,
            contextWindowTokens = 1_000_000,
        ),

        // ---- OpenRouter free roster (all $0/$0) -------------------------
        // Context windows are model-dependent; we only fill in ones we've
        // verified. Unknown stays null so the overflow check just relies
        // on the API's own 4xx.
        "openrouter/auto:free"        to ModelPricing(0.0, 0.0, null),
        "deepseek/deepseek-r1:free"   to ModelPricing(0.0, 0.0, 64_000),
        "meta-llama/llama-4-maverick:free" to ModelPricing(0.0, 0.0, 256_000),
        "google/gemma-3-27b-it"  to ModelPricing(0.0, 0.0, 128_000),
        "qwen/qwen3-235b-a22b:free"   to ModelPricing(0.0, 0.0, 128_000),
    )

    fun lookup(modelId: String): ModelPricing? = byId[modelId]

    /**
     * Apply [pricing] to a [usage] count and return the cost in USD.
     *
     * Thinking-token billing: Gemini bills `thoughtsTokens` at the output
     * rate (they're generated by the model, just not surfaced in the
     * response text). OpenRouter has no separate field, so for them
     * `thoughtsTokens` is always 0 and this collapses to the obvious
     * input + output split.
     */
    fun cost(usage: Usage, pricing: ModelPricing): Double =
        (usage.promptTokens * pricing.inputUsdPer1M
            + (usage.outputTokens + usage.thoughtsTokens) * pricing.outputUsdPer1M
        ) / 1_000_000.0
}
